### ISSUE TITLE
Timed out getting crumb.

### ISSUE THREAD

**Issue by Johnyboy1984** [iprak/yahoofinance#125]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.yahoofinance.coordinator
Quelle: custom_components/yahoofinance/coordinator.py:105
Integration: Yahoo Finance (Dokumentation, Probleme)
Erstmals aufgetreten: 22:00:59 (1 Vorkommnisse)
Zuletzt protokolliert: 22:00:59

Timed out getting crumb.

**Comment by iprak** [comment]
Do you see any delay in accessing the Yahoo finance the very time from your location?

**Comment by Johnyboy1984** [comment]
What do you mean by "Are you noticing a delay at your location?" ?

I notice that the sensors provide values, but the error is still in the log.

**Comment by iprak** [comment]
The integration retries getting cookie info and that is why sensors have value. This should coincide with the behavior when accessing Yahoo Finance website the very first time. If sensors report value then you will have to just ignore the error.  This could be related to your location where GPR authorization has been enforced.

**Comment by Johnyboy1984** [comment]
If I understand you correctly then the error is triggered by my location and if I still get values then I can just ignore this error? Correct?

**Comment by iprak** [comment]
The crumb cookie is needed for extracting data. "Timed out getting crumb" is the exception thrown if the request to obtain the cookie [did not complete in 15 seconds](https://github.com/iprak/yahoofinance/blob/93ad780c689a1acd2d4b411f24d5b9a1f87ab058/custom_components/yahoofinance/coordinator.py#L67). Whenever symbol data is refreshed, if the cookie is missing, then an attempt will be made to get it first.

If the error is not logged continuously, then the cookie request eventually succeeded, meaning we recovered and the error can be ignored. The initial failure will still get logged as an error.

For more investigation, you would have to use Networking monitoring tools like in Chrome Dev Tools and see what does the traffic for the very initial request look like.

**Comment by wburgers** [comment]
I'm experiencing this issue.

My sensors do not provide values.
It keeps failing to get the crumb. Many 1000s of times.

I don't know exactly when it started.
If it was yahoofinance 1.2.9 or HA 2024.5.4 that causes issues.
The last value for some sensors is the 17th of May, so that would indicate HA 2024.5.4.

I have set my home assistant logging config like:
```
logger:
  default: warn
  logs:
    custom_components.yahoofinance: debug
```
But that does not provide any additional logs.

I'll test if HA 2024.5.3 is better.

**Comment by wburgers** [comment]
And now it magically works again.

After a few days of not working and a few HA restarts.

Let's hope it keeps working 🤞

**Comment by iprak** [comment]
There has been no change in the integration regarding this. The request waits for 15 seconds before throwing that exception and then retries later.

**Comment by ctaggmk** [comment]
Here's the error I get on startup

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/yahoofinance/coordinator.py:85
Integration: yahoofinance (documentation, issues)
First occurred: 22:21:09 (1 occurrences)
Last logged: 22:21:09

Error during setup of component yahoofinance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/yahoofinance/__init__.py", line 290, in async_setup
    await _setup_coordinator()
  File "/config/custom_components/yahoofinance/__init__.py", line 238, in _setup_coordinator
    crumb = await crumb_coordinator.try_get_crumb_cookies()  # Get crumb first
  File "/config/custom_components/yahoofinance/coordinator.py", line 85, in try_get_crumb_cookies
    async with asyncio.timeout(WEBSESSION_TIMEOUT):
AttributeError: module 'asyncio' has no attribute 'timeout'

There are no sensor.yahoofinance entities listed

Looking back at the comments, are we suggesting an HA upgrade will help? I am running "Home Assistant 2023.4.6
Frontend 20230411.1 - latest" so am a little bit behind!

**Comment by iprak** [comment]
Yes the Core is quite old, that is from April 2023. It seems async.timeout is present in Python 3.11 which was adopted in 2023.6. I think updating core would be necessary.

**Comment by ctaggmk** [comment]
I've updated and still have this error from UI 
This error originated from a custom integration.

Logger: custom_components.yahoofinance
Source: custom_components/yahoofinance/__init__.py:241
integration: Yahoo Finance (documentation, issues)
First occurred: 19:28:06 (1 occurrences)
Last logged: 19:28:06

Unable to get crumb, re-trying in 15 seconds

and if I look in the logs I see these lines (non-Yahoo lines removed)
2024-10-13 19:27:55.714 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yahoofinance which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-13 19:28:06.234 WARNING (MainThread) [custom_components.yahoofinance] Unable to get crumb, re-trying in 15 seconds
2024-10-13 19:28:21.604 WARNING (MainThread) [custom_components.yahoofinance.coordinator] No data received for ['EXPN', 'GB00B02LCD75']

**Comment by iprak** [comment]
Was the data successfully obtained in subsequent fetch?

**Comment by petergCA** [comment]
Crumb issue popped up for me today

`This error originated from a custom integration.

Logger: custom_components.yahoofinance.coordinator
Source: custom_components/yahoofinance/coordinator.py:226
integration: Yahoo Finance (documentation, issues)
First occurred: 5:56:12 PM (191 occurrences)
Last logged: 8:57:49 PM

Crumb request responded with status=429, reason=Too Many Requests
Crumb request responded with status=404, reason=Not Found on Accelerator`

**Comment by Jay2645** [comment]
I am seeing this today as well.

```2025-04-29 22:03:57.117 INFO (MainThread) [custom_components.yahoofinance.coordinator] Accessing crumb page
2025-04-29 22:03:57.336 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Crumb request responded with status=429, reason=Too Many Requests
2025-04-29 22:03:57.336 WARNING (MainThread) [custom_components.yahoofinance] Unable to get crumb, re-trying in 60 seconds```

This repeats every 60 seconds.

My config:
```yahoofinance:
  scan_interval:
    minutes: 1
  show_trending_icon: true
  symbols:
    - DIS
    - "^DJI"
    - EA
    - GME
    - "^GSPC"
    - MSFT
    - NVDA
    - FBALX
    - RBLX
    - NTDOY
    - TTWO
    - KO
    - AMD
    - COST
    - JNJ
    - PEP
    - UNP
    - BRK.B
    - TSLA
    - AAPL
    - "NQ=F"```

**Comment by iprak** [comment]
Suggest increasing the scan interval. The [HttpCode 529](https://http.dev/529) indicates that the Server is overloaded.

**Comment by Jay2645** [comment]
Same here, bumped it up to 15 minutes to no avail. I've commented out the entire integration for now and am going to wait 24 hours to see if that solves it.

**Comment by Jay2645** [comment]
I've had the integration disabled for 24 hours and upon re-enabling it I was immediately hit with error 429 again. My scan interval is set to 15 minutes. I don't think it's any local settings? (It seems the retry is locked to every 60 seconds anyway)

```
2025-05-01 12:26:58.908 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Navigating to base page https://finance.yahoo.com/quote/NQ%3DF
2025-05-01 12:26:58.978 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Response 200, URL: https://finance.yahoo.com/quote/NQ=F
2025-05-01 12:26:58.978 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] No consent needed, have cookies=True
2025-05-01 12:26:58.979 INFO (MainThread) [custom_components.yahoofinance.coordinator] Accessing crumb page
2025-05-01 12:26:59.101 DEBUG (MainThread) [custom_components.yahoofinance.coordinator] Crumb response status: 429, <ClientResponse(https://query2.finance.yahoo.com/v1/test/getcrumb) [429 Too Many Requests]>
<CIMultiDictProxy('Date': 'Thu, 01 May 2025 19:26:59 GMT', 'Strict-Transport-Security': 'max-age=31536000', 'Server': 'ATS', 'Cache-Control': 'no-store', 'Content-Type': 'text/html', 'Content-Language': 'en', 'Referrer-Policy': 'no-referrer-when-downgrade', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Length': '19', 'Age': '1', 'Connection': 'keep-alive')>

2025-05-01 12:26:59.101 ERROR (MainThread) [custom_components.yahoofinance.coordinator] Crumb request responded with status=429, reason=Too Many Requests
2025-05-01 12:26:59.101 WARNING (MainThread) [custom_components.yahoofinance] Unable to get crumb, re-trying in 60 seconds
```

**Comment by iprak** [comment]
Is this still an issue?

**Comment by Johnyboy1984** [comment]
The problem seems to be resolved at the moment. Thank you for your effort and patience. Thank you very much.
