### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by johntdyer** [iprak/yahoofinance#26]
I am getting an error w/ Hassos v2021.02

The errors has something to do w/ the scan interval change introduced [here](https://github.com/iprak/yahoofinance/commit/c75e0345491afe8a989b9f63cc7ba0554c7c27cd)

```
2021-02-04 11:50:28 ERROR (MainThread) [homeassistant.setup] Error during setup of component yahoofinance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/yahoofinance/__init__.py", line 88, in async_setup
    scan_interval = parse_scan_interval(domain_config.get(CONF_SCAN_INTERVAL))
  File "/config/custom_components/yahoofinance/__init__.py", line 72, in parse_scan_interval
    elif scan_interval < MINIMUM_SCAN_INTERVAL:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'
```

my config is as follows:

```
sensor:
  - platform: yahoofinance
    show_trending_icon: true
    symbols:
      - CSCO
    scan_interval:
      hours: 1


```

I am running v1.01

Thanks

**Comment by iprak** [comment]
The configuration needs to be adjusted to something like this. This was breaking change in v 1.0.0

```yaml
yahoofinance:
  symbols:
    - ISTNX
```
