### ISSUE TITLE
Error on startup and calling yahoofinance.refresh_symbols service (introduced in v1.0.5)

### ISSUE THREAD

**Issue by robertwigley** [iprak/yahoofinance#36]
I am getting the following errors on startup and when calling the `yahoofinance.refresh_symbols` service, meaning that the prices are no longer updating. This problem appears to have been introducted in v1.0.5, as downgrading to v1.0.4 causes the errors to disappear and the prices to refresh again. I have highlighted the potential cause, which looks like it could be a typo / syntax error for the operator '+:'

2021-02-17 17:24:46 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform yahoofinance
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/yahoofinance/sensor.py", line 282, in async_added_to_hass
self._coordinator.async_add_listener(self.async_write_ha_state)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 83, in async_add_listener
self._schedule_refresh()
File "/config/custom_components/yahoofinance/__init__.py", line 228, in _schedule_refresh
utcnow().replace(microsecond=0) + self.get_next_update_interval(),
**TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'**

2021-02-17 17:24:46 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up yahoofinance platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 206, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/yahoofinance/sensor.py", line 282, in async_added_to_hass
self._coordinator.async_add_listener(self.async_write_ha_state)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 83, in async_add_listener
self._schedule_refresh()
File "/config/custom_components/yahoofinance/__init__.py", line 228, in _schedule_refresh
utcnow().replace(microsecond=0) + self.get_next_update_interval(),
**TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'**

2021-02-17 17:30:00 ERROR (MainThread) [homeassistant.components.automation.shares_update_prices] Shares: Update prices: Error executing script. Unexpected error for call_service at pos 1: unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/yahoofinance/__init__.py", line 148, in handle_refresh_symbols
await coordinator.async_request_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 131, in async_request_refresh
await self._debounced_refresh.async_call()
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 75, in async_call
await task
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in async_refresh
self._schedule_refresh()
File "/config/custom_components/yahoofinance/__init__.py", line 228, in _schedule_refresh
utcnow().replace(microsecond=0) + self.get_next_update_interval(),
**TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'**

2021-02-17 17:30:00 ERROR (MainThread) [homeassistant.components.automation.shares_update_prices] While executing automation automation.shares_update_prices
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 404, in async_trigger
await self.action_script.async_run(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1033, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 246, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/yahoofinance/__init__.py", line 148, in handle_refresh_symbols
await coordinator.async_request_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 131, in async_request_refresh
await self._debounced_refresh.async_call()
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 75, in async_call
await task
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in async_refresh
self._schedule_refresh()
File "/config/custom_components/yahoofinance/__init__.py", line 228, in _schedule_refresh
utcnow().replace(microsecond=0) + self.get_next_update_interval(),
**TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'**

**Comment by iprak** [comment]
Ahh you have update disabled, right?

**Comment by robertwigley** [comment]
Yes, I am calling the service to refresh the symbols on a schedule instead of using the automatic update.
