### ISSUE TITLE
Error on startup of plugin: "'YahooSymbolUpdateCoordinator' object has no attribute '_job'"

### ISSUE THREAD

**Issue by mwaterreus** [iprak/yahoofinance#40]
I get the following error after updating the plugin to version 1.0.7. I came from 1.0.0 so had to reconfigure my configuration.yaml. After starting homeassistant the following error pops up.

```
 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up yahoofinance platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yahoofinance/sensor.py", line 286, in async_added_to_hass
    self._coordinator.async_add_listener(self.async_write_ha_state)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 77, in async_add_listener
    self._schedule_refresh()
  File "/config/custom_components/yahoofinance/__init__.py", line 229, in _schedule_refresh
    self._job,
AttributeError: 'YahooSymbolUpdateCoordinator' object has no attribute '_job'
```

Configfile is as follows

```
show_trending_icon: true
scan_interval:
  minutes: 1
symbols:
  - USDEUR=X
  - symbol: TSLA
    target_currency: EUR
  - symbol: GOOGL
    target_currency: EUR
  - symbol: MSFT
    target_currency: EUR
  - BTC-EUR
  - ETH-EUR
```

**Comment by mwaterreus** [comment]
Been doing a bit more searchwork. It seems the updater breaks with the above error.

The error is introduced in version 1.0.5 here since 1.0.4 is not showing any problems when I downgrade to that version.

I am (still) running HomeAssistant 0.116.2 here in case that matters.

**Comment by mwaterreus** [comment]
upgrading to latest version of homeassistant (2021.3.4) fixed this issue; can be closed.
