### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by vietde** [iprak/yahoofinance#61]
I just install HACS and when I restart the server and here is the issue. Please advise 
`Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/__init__.py", line 171, in async_setup
    scan_interval = parse_scan_interval(domain_config.get(CONF_SCAN_INTERVAL))
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/__init__.py", line 136, in parse_scan_interval
    elif scan_interval < MINIMUM_SCAN_INTERVAL:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'
`

**Comment by iprak** [comment]
What is your configuration?

**Comment by vietde** [comment]
Here is my YAML config
<img width="320" alt="image" src="https://user-images.githubusercontent.com/33403977/146390020-8aaf84ce-2a81-46f9-a712-59891544f93b.png">
