### ISSUE TITLE
After update 2021.12.2 setup failed: unknown error

### ISSUE THREAD

**Issue by ibl129** [iprak/yahoofinance#62]
Since I updated to 2021.12.2 I can’t get any data. The following error occurs. 

Logger: homeassistant.setup
Source: custom_components/yahoofinance/coordinator.py:36 
Integration: yahoofinance (documentation, issues) 
First occurred: 15 december 2021 22:07:54 (1 occurrences) 
Last logged: 15 december 2021 22:07:54

Setup failed for yahoofinance: unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 181, in _async_setup_component
    component = integration.get_component()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/__init__.py", line 18, in <module>
    from custom_components.yahoofinance.coordinator import YahooSymbolUpdateCoordinator
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/coordinator.py", line 32, in <module>
    class YahooSymbolUpdateCoordinator(DataUpdateCoordinator):
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/coordinator.py", line 36, in YahooSymbolUpdateCoordinator
    def parse_symbol_data(symbol_data: dict) -> dict[str, any]:
TypeError: 'type' object is not subscriptable

**Comment by iprak** [comment]
You can enable debug level logging to see what might be happening. e.g.
```
logger:
  default: warn
  logs:
    custom_components.yahoofinance: debug
```

It does seem that empty data is being returned from yahoo endpoint.

**Comment by ibl129** [comment]
hi @iprak I changed the logger settings and it's giving me the following information:

`Setup failed for yahoofinance: unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 181, in _async_setup_component
    component = integration.get_component()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/__init__.py", line 18, in <module>
    from custom_components.yahoofinance.coordinator import YahooSymbolUpdateCoordinator
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/coordinator.py", line 32, in <module>
    class YahooSymbolUpdateCoordinator(DataUpdateCoordinator):
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/coordinator.py", line 36, in YahooSymbolUpdateCoordinator
    def parse_symbol_data(symbol_data: dict) -> dict[str, any]:
TypeError: 'type' object is not subscriptable`

have you got any clue?

**Comment by iprak** [comment]
No. if possible then would you mind staring your configuration related to yahoofinance?

**Comment by ibl129** [comment]
This is the configuration I implemented:

`yahoofinance:
  scan_interval:
    minutes: 5
  decimal_places: 3
  symbols:
    - symbol: VUSA.AS
      target_currency: EUR
    - symbol: VHYL.AS
      target_currency: EUR
    - symbol: VECP.AS
      target_currency: EUR
    - symbol: VUTY.AS
      target_currency: EUR
    - symbol: CNDX.AS
      target_currency: EUR`

The raw log gives me the following error:
`2021-12-16 21:47:52 ERROR (MainThread) [homeassistant.setup] Setup failed for yahoofinance: unknown error
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/__init__.py", line 18, in <module>
    from custom_components.yahoofinance.coordinator import YahooSymbolUpdateCoordinator
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/coordinator.py", line 32, in <module>
    class YahooSymbolUpdateCoordinator(DataUpdateCoordinator):
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/coordinator.py", line 36, in YahooSymbolUpdateCoordinator`

Before I updated to version 2021.12.2 the integration worked fully perfect. So it seems to be a matter with regards to the latest update.

**Comment by iprak** [comment]
I am not sure why loading the component is crashing. Yes the component is just being loaded which is why debug logging did not show anything more. 

I did not find anything matching in HomeAssitant issues list. Your configuration is straight forward but I was not able to replicate the crash in Docket or my raspberrypi. I have a couple thing you can try

a) Remove yahoofinance component, restart  and then add it back.
b) Edit that function at line 36 in `coordinator.py` to be just `def parse_symbol_data(symbol_data: dict )-> dict:`

**Comment by ibl129** [comment]
I tried the two options. The first option did not give any solution. The second one gave me the following error, which seems to be slightly different from the first error. But after all; not a solution as you can see. 

```
Logger: homeassistant.setup
Source: custom_components/yahoofinance/coordinator.py:79 
Integration: yahoofinance (documentation, issues) 
First occurred: 17:11:12 (1 occurrences) 
Last logged: 17:11:12

Setup failed for yahoofinance: unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 181, in _async_setup_component
    component = integration.get_component()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/__init__.py", line 18, in <module>
    from custom_components.yahoofinance.coordinator import YahooSymbolUpdateCoordinator
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/coordinator.py", line 32, in <module>
    class YahooSymbolUpdateCoordinator(DataUpdateCoordinator):
  File "/home/homeassistant/.homeassistant/custom_components/yahoofinance/coordinator.py", line 79, in YahooSymbolUpdateCoordinator
    self, symbols: list[str], hass: HomeAssistant, update_interval: timedelta
TypeError: 'type' object is not subscriptable
```

**Comment by iprak** [comment]
I am out of ideas.  But I posted this on the homeassistant interations discord channel.

**Comment by dzirtt** [comment]
Problem is code not compatible with python3.8 or lower, in python 3.9 added:
"Type Hinting Generics in Standard Collections" - for our case is dict

```
def parse_symbol_data(symbol_data: dict) -> dict[str, any]:

#for compatible you can use
importm typing
def parse_symbol_data(symbol_data:typing.Dict) -> typing.Dict[str,any]:

```

```
root@orangepipc2:/tmp/yahoo# python3.8 test.py 
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    def parse_symbol_data(symbol_data) -> dict[str,any]:
TypeError: 'type' object is not subscriptable
root@orangepipc2:/tmp/yahoo# python3.9 test.py 
pass

```

**Comment by iprak** [comment]
That's sound like the reason. I use the docker and hassos which are at 3.9.6. 

It seems that the fix is to include `from __future__ import annotations` at the top of the file.

**Comment by iprak** [comment]
@ibl129  @dzirtt Can you guys confirm that you have python < 3.9 ? Also what is your HomeAssistant installation installed on?

**Comment by ibl129** [comment]
Yes I am using python 3.8 and run Home Assistant in a venv environment on a Ubuntu 16.04 server.

**Comment by iprak** [comment]
Thanks. I was able to recreate the issue and have released a fix.

**Comment by ibl129** [comment]
Wonderful! You solved it by releasing the update of today. Thank you very much!!
